name: Deploy to EC2 via Bastion

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key

      - name: Deploy to EC2 via Bastion
        run: |
          ssh -i ~/.ssh/key \
          -o StrictHostKeyChecking=no \
          -o ProxyJump=${{ secrets.EC2_USER }}@${{ secrets.BASTION_HOST }} \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            cd ~/dev
