name: CI/CD Deploy to Private EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Deploy via Bastion
      - name: Deploy via Bastion
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.BASTION_IP }}
          username: ubuntu
          key: ${{ secrets.BASTION_KEY }}
          script: |
            echo "Connecting to private EC2..."
            ssh -o StrictHostKeyChecking=no ubuntu@10.0.141.140 << 'EOF'
              echo "Navigating to app folder"
              cd ~/app

              echo "Stopping old Docker containers (if any)"
              sudo docker ps -aq | xargs -r sudo docker rm -f

              echo "Building Docker image"
              sudo docker build -t my-app .

              echo "Running Docker container on port 80"
              sudo docker run -d -p 80:80 my-app

              echo "Deployment complete"
            EOF
