name: CI/CD Deploy to Private EC2

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Deploy via Bastion Host
    uses: appleboy/ssh-action@v0.1.6

    with:
      host: ${{ secrets.BASTION_IP }}
      username: ubuntu
      key: ${{ secrets.BASTION_KEY }}
      port: 22

      script: |

        echo "✅ Connected to Bastion"

        # Update repository on Bastion
        cd ~/devops-private-nginx-site

        git fetch origin main
        git reset --hard origin/main

        echo "✅ Bastion repo updated"

        # Sync files to Private EC2
        rsync -avz --delete \
          -e "ssh -i ~/.ssh/github-key -o StrictHostKeyChecking=no" \
          ~/devops-private-nginx-site/ \
          ubuntu@${{ secrets.EC2_HOST }}:~/devops-private-nginx-site/

        echo "✅ Files synced to Private EC2"

        # Deploy on Private EC2
        ssh -i ~/.ssh/github-key -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'

          echo "✅ Inside Private EC2"

          cd ~/devops-private-nginx-site

          chmod +x deploy.sh

          ./deploy.sh

        EOF
```

